spring.application.name=invoicetracker
spring.datasource.url=jdbc:postgresql://localhost:5432/invoice_tracker
spring.datasource.username=atishayjain
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true